name: Context
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.workspace }}"
      - run: echo "${{ github.run_id }}"